/* SUPONGA UN ARREGLO DE 10 ELEMENTOS CUYOS VALORES PUEDAN SER INGRESADOS
   POR TECLADO O ESTAR PREDETERMINADO CON LOS SIGUIENTES VALORES:
   65   98   32   41   95   74   32   95   10   18
   POR OTRA PARTE, SE TIENE UN SEGUNDO ARREGLO DE 6 ELEMENTOS CUYOS
   VALORES PUEDAN SER INGRESADOS POR TECLADO O ESTAR PREDETERMINADO
   CON LOS SIGUIENTES VALORES:
   5   0   4   6   0   4
   REALIZAR UN PROGRAMA QUE HAGA LA DIVISION DEL PRIMER ARREGLO
   ENTRE EL SEGUNDO. DEBE TENER EN CUENTA LAS POSIBLES EXCEPCIONES QUE
   SE PUEDAN GENERAR.
*/
