/* CREAR UN OBJETO CON LOS SIGUIENTES DATOS:
	NOMBRE, APELLIDO, SEXO, EDAD.
   LA CLASE DEBE CONTENER EL METODO
    MOSTRAR -> DEBE MOSTRAR TODOS LOS DATOS
   POR OTRA PARTE, SE DEBE CREAR EL OBJETO TELEFONO CON LOS SIGUIENTES
   DATOS:
    TEL_CEL, TEL_OFI, TEL_HAB MAS LOS DATOS DEL PRIMER OBJETO
   LA CLASE DEBE TENER EL METODO:
    MOSTRAR -> DEBE MOSTRAR TODOS LOS DATOS, INCLUYENDO LOS HEREDADOS
   PARA TERMINAR SE DEBE CREAR LA CLASE PRINCIPAL, DONDE SE TENDRA QUE
   LEER LOS DATOS A UTILIZAR Y REALIZAR UN METODO QUE PERMITA BUSCAR
   EL TELEFONO DE UNA PERSONA EXPECIFICA.
   FINALMENTE SE DEBE MOSTRAR LOS DATOS ORDENADOS ALFABETICAMENTE POR EL
   APELLIDO
*/
